services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: training_user
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: training_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./trainingPG/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U training_user -d training_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: ./trainingPG
    ports:
      - "8080:8080"
    env_file:
      - ./trainingPG/.env.dev
    environment:
      PG_HOST: postgres
      PG_NAME: training_db
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: