-- Training domain: short-term home rentals.
-- Goose migration: rental schema and a small deterministic reference dataset.

-- +goose Up

CREATE TABLE IF NOT EXISTS cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL DEFAULT 'Россия',
    CONSTRAINT cities_name_country_key UNIQUE (name, country)
);

CREATE TABLE IF NOT EXISTS properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES users(uid),
    city_id BIGINT NOT NULL REFERENCES cities(id),
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    address VARCHAR(300) NOT NULL,
    room_count SMALLINT NOT NULL CHECK (room_count > 0),
    max_guests SMALLINT NOT NULL CHECK (max_guests > 0),
    price_per_night NUMERIC(12, 2) NOT NULL CHECK (price_per_night > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT properties_owner_title_key UNIQUE (owner_id, title)
);

CREATE TABLE IF NOT EXISTS amenities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS property_amenities (
    property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    amenity_id BIGINT NOT NULL REFERENCES amenities(id),
    PRIMARY KEY (property_id, amenity_id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES properties(id),
    guest_id UUID NOT NULL REFERENCES users(uid),
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    guests_count SMALLINT NOT NULL CHECK (guests_count > 0),
    status VARCHAR(20) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bookings_dates_check CHECK (check_out > check_in),
    CONSTRAINT bookings_status_check
        CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE REFERENCES bookings(id),
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    status VARCHAR(20) NOT NULL,
    paid_at TIMESTAMPTZ,
    CONSTRAINT payments_status_check
        CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded'))
);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE REFERENCES bookings(id),
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Stable training users. Dependent rows find them by email, so this seed also
-- works when an email already exists with another UUID.
INSERT INTO users (uid, name, email, created_at)
VALUES
    ('10000000-0000-0000-0000-000000000001', 'Анна Волкова', 'anna@example.com', '2025-01-10 09:00:00+03'),
    ('10000000-0000-0000-0000-000000000002', 'Борис Орлов', 'boris@example.com', '2025-01-12 10:00:00+03'),
    ('10000000-0000-0000-0000-000000000003', 'Виктор Соколов', 'viktor@example.com', '2025-01-15 11:00:00+03'),
    ('10000000-0000-0000-0000-000000000004', 'Галина Морозова', 'galina@example.com', '2025-02-01 12:00:00+03'),
    ('10000000-0000-0000-0000-000000000005', 'Денис Лебедев', 'denis@example.com', '2025-02-03 13:00:00+03'),
    ('10000000-0000-0000-0000-000000000006', 'Елена Крылова', 'elena@example.com', '2025-02-05 14:00:00+03')
ON CONFLICT DO NOTHING;

INSERT INTO cities (id, name, country)
VALUES
    (1, 'Москва', 'Россия'),
    (2, 'Санкт-Петербург', 'Россия'),
    (3, 'Казань', 'Россия')
ON CONFLICT DO NOTHING;

INSERT INTO amenities (id, name)
VALUES
    (1, 'Wi-Fi'),
    (2, 'Кондиционер'),
    (3, 'Парковка'),
    (4, 'Кухня'),
    (5, 'Стиральная машина'),
    (6, 'Можно с животными'),
    (7, 'Рабочее место')
ON CONFLICT DO NOTHING;

INSERT INTO properties (
    id, owner_id, city_id, title, description, address,
    room_count, max_guests, price_per_night, is_active, created_at
)
VALUES
    (1, (SELECT uid FROM users WHERE email = 'anna@example.com'), 1,
     'Лофт у Арбата', 'Небольшой лофт в центре', 'ул. Арбат, 10',
     1, 2, 5500.00, TRUE, '2025-02-10 10:00:00+03'),
    (2, (SELECT uid FROM users WHERE email = 'anna@example.com'), 1,
     'Семейная квартира', 'Тихий двор и две спальни', 'ул. Большая Якиманка, 25',
     3, 5, 8200.00, TRUE, '2025-02-12 10:00:00+03'),
    (3, (SELECT uid FROM users WHERE email = 'boris@example.com'), 2,
     'Студия на Петроградке', 'Студия рядом с метро', 'Каменноостровский пр., 18',
     1, 2, 4200.00, TRUE, '2025-02-15 10:00:00+03'),
    (4, (SELECT uid FROM users WHERE email = 'boris@example.com'), 2,
     'Квартира у Невы', 'Две комнаты с видом на реку', 'Воскресенская наб., 8',
     2, 4, 6500.00, TRUE, '2025-02-17 10:00:00+03'),
    (5, (SELECT uid FROM users WHERE email = 'viktor@example.com'), 3,
     'Домик в Старо-Татарской слободе', 'Отдельный небольшой дом', 'ул. Каюма Насыри, 14',
     2, 3, 3500.00, TRUE, '2025-02-20 10:00:00+03'),
    (6, (SELECT uid FROM users WHERE email = 'viktor@example.com'), 1,
     'Комната на Таганке', 'Объявление временно снято', 'ул. Таганская, 31',
     1, 1, 3000.00, FALSE, '2025-02-21 10:00:00+03'),
    (7, (SELECT uid FROM users WHERE email = 'viktor@example.com'), 3,
     'Большой дом у озера', 'Дом для семьи или компании', 'Озёрная ул., 7',
     4, 6, 9000.00, TRUE, '2025-03-01 10:00:00+03')
ON CONFLICT DO NOTHING;

INSERT INTO property_amenities (property_id, amenity_id)
VALUES
    (1, 1), (1, 2), (1, 4), (1, 7),
    (2, 1), (2, 3), (2, 4), (2, 5),
    (3, 1), (3, 4), (3, 7),
    (4, 1), (4, 2), (4, 4), (4, 5),
    (5, 1), (5, 3), (5, 4), (5, 6),
    (6, 1),
    (7, 3), (7, 4), (7, 5), (7, 6)
ON CONFLICT DO NOTHING;

INSERT INTO bookings (
    id, property_id, guest_id, check_in, check_out,
    guests_count, status, total_amount, created_at
)
VALUES
    (1, 1, (SELECT uid FROM users WHERE email = 'galina@example.com'),
     '2025-06-01', '2025-06-05', 2, 'completed', 22000.00, '2025-05-01 10:00:00+03'),
    (2, 1, (SELECT uid FROM users WHERE email = 'denis@example.com'),
     '2025-06-10', '2025-06-13', 1, 'cancelled', 16500.00, '2025-05-03 10:00:00+03'),
    (3, 1, (SELECT uid FROM users WHERE email = 'elena@example.com'),
     '2025-07-02', '2025-07-07', 2, 'completed', 27500.00, '2025-05-10 10:00:00+03'),
    (4, 2, (SELECT uid FROM users WHERE email = 'denis@example.com'),
     '2025-06-20', '2025-06-24', 4, 'completed', 32800.00, '2025-05-12 10:00:00+03'),
    (5, 2, (SELECT uid FROM users WHERE email = 'galina@example.com'),
     '2025-07-10', '2025-07-15', 3, 'confirmed', 41000.00, '2025-05-15 10:00:00+03'),
    (6, 3, (SELECT uid FROM users WHERE email = 'elena@example.com'),
     '2025-06-03', '2025-06-08', 1, 'completed', 21000.00, '2025-05-18 10:00:00+03'),
    (7, 3, (SELECT uid FROM users WHERE email = 'galina@example.com'),
     '2025-08-01', '2025-08-04', 2, 'cancelled', 12600.00, '2025-05-20 10:00:00+03'),
    (8, 4, (SELECT uid FROM users WHERE email = 'denis@example.com'),
     '2025-06-12', '2025-06-18', 4, 'completed', 39000.00, '2025-05-22 10:00:00+03'),
    (9, 4, (SELECT uid FROM users WHERE email = 'elena@example.com'),
     '2025-07-20', '2025-07-22', 2, 'confirmed', 13000.00, '2025-06-01 10:00:00+03'),
    (10, 5, (SELECT uid FROM users WHERE email = 'galina@example.com'),
     '2025-06-05', '2025-06-10', 2, 'completed', 17500.00, '2025-05-25 10:00:00+03'),
    (11, 5, (SELECT uid FROM users WHERE email = 'elena@example.com'),
     '2025-09-01', '2025-09-03', 3, 'confirmed', 7000.00, '2025-06-05 10:00:00+03')
ON CONFLICT DO NOTHING;

INSERT INTO payments (id, booking_id, amount, status, paid_at)
VALUES
    (1, 1, 22000.00, 'succeeded', '2025-05-01 10:05:00+03'),
    (2, 3, 27500.00, 'succeeded', '2025-05-10 10:05:00+03'),
    (3, 4, 32800.00, 'succeeded', '2025-05-12 10:05:00+03'),
    (4, 5, 41000.00, 'succeeded', '2025-05-15 10:05:00+03'),
    (5, 6, 21000.00, 'succeeded', '2025-05-18 10:05:00+03'),
    (6, 8, 39000.00, 'succeeded', '2025-05-22 10:05:00+03'),
    (7, 9, 13000.00, 'pending', NULL),
    (8, 10, 17500.00, 'succeeded', '2025-05-25 10:05:00+03')
ON CONFLICT DO NOTHING;

INSERT INTO reviews (id, booking_id, rating, comment, created_at)
VALUES
    (1, 1, 5, 'Отличное расположение', '2025-06-06 12:00:00+03'),
    (2, 3, 4, 'Всё понравилось, но было шумно', '2025-07-08 12:00:00+03'),
    (3, 4, 5, 'Удобно для семьи', '2025-06-25 12:00:00+03'),
    (4, 6, 4, 'Чисто и близко к метро', '2025-06-09 12:00:00+03'),
    (5, 8, 5, 'Прекрасный вид', '2025-06-19 12:00:00+03'),
    (6, 10, 4, 'Уютный дом и хороший хозяин', '2025-06-11 12:00:00+03')
ON CONFLICT DO NOTHING;

-- Explicit IDs above do not advance identity sequences. Move them forward so
-- students can safely INSERT rows without supplying IDs.
SELECT setval(pg_get_serial_sequence('cities', 'id'), (SELECT MAX(id) FROM cities), TRUE);
SELECT setval(pg_get_serial_sequence('properties', 'id'), (SELECT MAX(id) FROM properties), TRUE);
SELECT setval(pg_get_serial_sequence('amenities', 'id'), (SELECT MAX(id) FROM amenities), TRUE);
SELECT setval(pg_get_serial_sequence('bookings', 'id'), (SELECT MAX(id) FROM bookings), TRUE);
SELECT setval(pg_get_serial_sequence('payments', 'id'), (SELECT MAX(id) FROM payments), TRUE);
SELECT setval(pg_get_serial_sequence('reviews', 'id'), (SELECT MAX(id) FROM reviews), TRUE);

-- +goose Down

DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS property_amenities;
DROP TABLE IF EXISTS amenities;
DROP TABLE IF EXISTS properties;
DROP TABLE IF EXISTS cities;

DELETE FROM users
WHERE email IN (
    'anna@example.com',
    'boris@example.com',
    'viktor@example.com',
    'galina@example.com',
    'denis@example.com',
    'elena@example.com'
);
